---
- name: Template wordfence-waf.php
  ansible.builtin.template:
    src: "{{ role_path }}/templates/wordfence-waf.php.j2"
    dest: "{{ deploy_helper.new_release_path }}/web/wp/wordfence-waf.php"
    mode: "0755"
