name: Releases

on:
  push:
    tags:
      - "*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get tag
        id: get_tag
        run: echo ::set-output name=value::${GITHUB_REF/refs\/tags\//}

      - name: Create archive
        run: zip -r -9 trellis-wordfence-kinsta.zip *

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: Version ${{ steps.get_tag.value }}
          files: trellis-wordfence-kinsta.zip
